version: 2

updates:
  - package-ecosystem: github-actions
    directories: ["/"]
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]
    labels: ["dependencies"]

  - package-ecosystem: gomod
    directories: [".", "./.sage"]
    schedule:
      interval: monthly
    groups:
      gomod-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies"]
