version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns:
          - "*"  # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns:
          - "*"  # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"
