before:
  hooks:
    - go mod download

builds:
  - id: aip-spanner-go
    binary: aip-spanner-go
    main: ./cmd/aip-spanner-go/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
  prerelease: auto
