// +build testdata1.sql

package testdata

// Code generated by TestGenerateDatabaseDescriptor/testdata/1.sql. DO NOT EDIT.

import (
	"cloud.google.com/go/spanner/spansql"
)

var (
	_ = spansql.ID("")
)

func Descriptor() DatabaseDescriptor {
	return &descriptor
}

var descriptor = databaseDescriptor{
	singers: singersTableDescriptor{
		tableID: "Singers",
		singerId: singersSingerIdColumnDescriptor{
			columnID:   "SingerId",
			columnType: spansql.Type{Array: false, Base: 1, Len: 0},
			notNull:    true,
			options:    spansql.ColumnOptions{AllowCommitTimestamp: (*bool)(nil)},
		},
		firstName: singersFirstNameColumnDescriptor{
			columnID:   "FirstName",
			columnType: spansql.Type{Array: false, Base: 3, Len: 1024},
			notNull:    false,
			options:    spansql.ColumnOptions{AllowCommitTimestamp: (*bool)(nil)},
		},
		lastName: singersLastNameColumnDescriptor{
			columnID:   "LastName",
			columnType: spansql.Type{Array: false, Base: 3, Len: 1024},
			notNull:    false,
			options:    spansql.ColumnOptions{AllowCommitTimestamp: (*bool)(nil)},
		},
		singerInfo: singersSingerInfoColumnDescriptor{
			columnID:   "SingerInfo",
			columnType: spansql.Type{Array: false, Base: 4, Len: 9223372036854775807},
			notNull:    false,
			options:    spansql.ColumnOptions{AllowCommitTimestamp: (*bool)(nil)},
		},
	},
}

type DatabaseDescriptor interface {
	Singers() SingersTableDescriptor
}

type databaseDescriptor struct {
	singers singersTableDescriptor
}

func (d *databaseDescriptor) Singers() SingersTableDescriptor {
	return &d.singers
}

type ColumnDescriptor interface {
	ColumnID() spansql.ID
	ColumnName() string
	ColumnType() spansql.Type
	NotNull() bool
	Options() spansql.ColumnOptions
}

type SingersTableDescriptor interface {
	TableName() string
	TableID() spansql.ID
	ColumnNames() []string
	ColumnIDs() []spansql.ID
	SingerId() ColumnDescriptor
	FirstName() ColumnDescriptor
	LastName() ColumnDescriptor
	SingerInfo() ColumnDescriptor
}

type singersTableDescriptor struct {
	tableID    spansql.ID
	singerId   singersSingerIdColumnDescriptor
	firstName  singersFirstNameColumnDescriptor
	lastName   singersLastNameColumnDescriptor
	singerInfo singersSingerInfoColumnDescriptor
}

func (d *singersTableDescriptor) TableName() string {
	return string(d.tableID)
}

func (d *singersTableDescriptor) TableID() spansql.ID {
	return d.tableID
}

func (d *singersTableDescriptor) ColumnNames() []string {
	return []string{
		"SingerId",
		"FirstName",
		"LastName",
		"SingerInfo",
	}
}

func (d *singersTableDescriptor) ColumnIDs() []spansql.ID {
	return []spansql.ID{
		"SingerId",
		"FirstName",
		"LastName",
		"SingerInfo",
	}
}

func (d *singersTableDescriptor) SingerId() ColumnDescriptor {
	return &d.singerId
}

func (d *singersTableDescriptor) FirstName() ColumnDescriptor {
	return &d.firstName
}

func (d *singersTableDescriptor) LastName() ColumnDescriptor {
	return &d.lastName
}

func (d *singersTableDescriptor) SingerInfo() ColumnDescriptor {
	return &d.singerInfo
}

type singersSingerIdColumnDescriptor struct {
	columnID   spansql.ID
	columnType spansql.Type
	notNull    bool
	options    spansql.ColumnOptions
}

func (d *singersSingerIdColumnDescriptor) ColumnName() string {
	return string(d.columnID)
}

func (d *singersSingerIdColumnDescriptor) ColumnID() spansql.ID {
	return d.columnID
}

func (d *singersSingerIdColumnDescriptor) ColumnType() spansql.Type {
	return d.columnType
}

func (d *singersSingerIdColumnDescriptor) NotNull() bool {
	return d.notNull
}

func (d *singersSingerIdColumnDescriptor) Options() spansql.ColumnOptions {
	return d.options
}

type singersFirstNameColumnDescriptor struct {
	columnID   spansql.ID
	columnType spansql.Type
	notNull    bool
	options    spansql.ColumnOptions
}

func (d *singersFirstNameColumnDescriptor) ColumnName() string {
	return string(d.columnID)
}

func (d *singersFirstNameColumnDescriptor) ColumnID() spansql.ID {
	return d.columnID
}

func (d *singersFirstNameColumnDescriptor) ColumnType() spansql.Type {
	return d.columnType
}

func (d *singersFirstNameColumnDescriptor) NotNull() bool {
	return d.notNull
}

func (d *singersFirstNameColumnDescriptor) Options() spansql.ColumnOptions {
	return d.options
}

type singersLastNameColumnDescriptor struct {
	columnID   spansql.ID
	columnType spansql.Type
	notNull    bool
	options    spansql.ColumnOptions
}

func (d *singersLastNameColumnDescriptor) ColumnName() string {
	return string(d.columnID)
}

func (d *singersLastNameColumnDescriptor) ColumnID() spansql.ID {
	return d.columnID
}

func (d *singersLastNameColumnDescriptor) ColumnType() spansql.Type {
	return d.columnType
}

func (d *singersLastNameColumnDescriptor) NotNull() bool {
	return d.notNull
}

func (d *singersLastNameColumnDescriptor) Options() spansql.ColumnOptions {
	return d.options
}

type singersSingerInfoColumnDescriptor struct {
	columnID   spansql.ID
	columnType spansql.Type
	notNull    bool
	options    spansql.ColumnOptions
}

func (d *singersSingerInfoColumnDescriptor) ColumnName() string {
	return string(d.columnID)
}

func (d *singersSingerInfoColumnDescriptor) ColumnID() spansql.ID {
	return d.columnID
}

func (d *singersSingerInfoColumnDescriptor) ColumnType() spansql.Type {
	return d.columnType
}

func (d *singersSingerInfoColumnDescriptor) NotNull() bool {
	return d.notNull
}

func (d *singersSingerInfoColumnDescriptor) Options() spansql.ColumnOptions {
	return d.options
}
