// Code generated by TestTableDescriptorCodeGenerator_GenerateCode/table/testdata/2.sql. DO NOT EDIT.
//go:build testdata.2.sql.table
// +build testdata.2.sql.table

package testdata

import (
	"cloud.google.com/go/spanner/spansql"
)

type SingersTableDescriptor interface {
	TableName() string
	TableID() spansql.ID
	ColumnNames() []string
	ColumnIDs() []spansql.ID
	ColumnExprs() []spansql.Expr
	SingerId() ColumnDescriptor
	FirstName() ColumnDescriptor
	LastName() ColumnDescriptor
	SingerInfo() ColumnDescriptor
}

type singersTableDescriptor struct {
	tableID    spansql.ID
	singerId   columnDescriptor
	firstName  columnDescriptor
	lastName   columnDescriptor
	singerInfo columnDescriptor
}

func (d *singersTableDescriptor) TableName() string {
	return string(d.tableID)
}

func (d *singersTableDescriptor) TableID() spansql.ID {
	return d.tableID
}

func (d *singersTableDescriptor) ColumnNames() []string {
	return []string{
		"SingerId",
		"FirstName",
		"LastName",
		"SingerInfo",
	}
}

func (d *singersTableDescriptor) ColumnIDs() []spansql.ID {
	return []spansql.ID{
		"SingerId",
		"FirstName",
		"LastName",
		"SingerInfo",
	}
}

func (d *singersTableDescriptor) ColumnExprs() []spansql.Expr {
	return []spansql.Expr{
		spansql.ID("SingerId"),
		spansql.ID("FirstName"),
		spansql.ID("LastName"),
		spansql.ID("SingerInfo"),
	}
}

func (d *singersTableDescriptor) SingerId() ColumnDescriptor {
	return &d.singerId
}

func (d *singersTableDescriptor) FirstName() ColumnDescriptor {
	return &d.firstName
}

func (d *singersTableDescriptor) LastName() ColumnDescriptor {
	return &d.lastName
}

func (d *singersTableDescriptor) SingerInfo() ColumnDescriptor {
	return &d.singerInfo
}

type AlbumsTableDescriptor interface {
	TableName() string
	TableID() spansql.ID
	ColumnNames() []string
	ColumnIDs() []spansql.ID
	ColumnExprs() []spansql.Expr
	SingerId() ColumnDescriptor
	AlbumId() ColumnDescriptor
	AlbumTitle() ColumnDescriptor
}

type albumsTableDescriptor struct {
	tableID    spansql.ID
	singerId   columnDescriptor
	albumId    columnDescriptor
	albumTitle columnDescriptor
}

func (d *albumsTableDescriptor) TableName() string {
	return string(d.tableID)
}

func (d *albumsTableDescriptor) TableID() spansql.ID {
	return d.tableID
}

func (d *albumsTableDescriptor) ColumnNames() []string {
	return []string{
		"SingerId",
		"AlbumId",
		"AlbumTitle",
	}
}

func (d *albumsTableDescriptor) ColumnIDs() []spansql.ID {
	return []spansql.ID{
		"SingerId",
		"AlbumId",
		"AlbumTitle",
	}
}

func (d *albumsTableDescriptor) ColumnExprs() []spansql.Expr {
	return []spansql.Expr{
		spansql.ID("SingerId"),
		spansql.ID("AlbumId"),
		spansql.ID("AlbumTitle"),
	}
}

func (d *albumsTableDescriptor) SingerId() ColumnDescriptor {
	return &d.singerId
}

func (d *albumsTableDescriptor) AlbumId() ColumnDescriptor {
	return &d.albumId
}

func (d *albumsTableDescriptor) AlbumTitle() ColumnDescriptor {
	return &d.albumTitle
}

type ColumnDescriptor interface {
	ColumnID() spansql.ID
	ColumnName() string
	ColumnType() spansql.Type
	NotNull() bool
	AllowCommitTimestamp() bool
}

type columnDescriptor struct {
	columnID             spansql.ID
	columnType           spansql.Type
	notNull              bool
	allowCommitTimestamp bool
}

func (d *columnDescriptor) ColumnName() string {
	return string(d.columnID)
}

func (d *columnDescriptor) ColumnID() spansql.ID {
	return d.columnID
}

func (d *columnDescriptor) ColumnType() spansql.Type {
	return d.columnType
}

func (d *columnDescriptor) ColumnExpr() spansql.Expr {
	return d.columnID
}

func (d *columnDescriptor) NotNull() bool {
	return d.notNull
}

func (d *columnDescriptor) AllowCommitTimestamp() bool {
	return d.allowCommitTimestamp
}
