name: release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: 1.19

      - name: Make
        run: make

      - name: Release
        id: semantic-release
        uses: go-semantic-release/action@v1.21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4.3.0
        # Only run if a new version was tagged.
        if: ${{ steps.semantic-release.outputs.version != '' }}
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
