package musicdb

// Code generated by spanner-aip-go. DO NOT EDIT.

import (
	"cloud.google.com/go/spanner/spansql"
)

func Descriptor() DatabaseDescriptor {
	return &descriptor
}

var descriptor = databaseDescriptor{
	singers: singersTableDescriptor{
		tableID: "Singers",
		singerId: columnDescriptor{
			columnID:             "SingerId",
			columnType:           spansql.Type{Array: false, Base: 1, Len: 0},
			notNull:              true,
			allowCommitTimestamp: false,
		},
		firstName: columnDescriptor{
			columnID:             "FirstName",
			columnType:           spansql.Type{Array: false, Base: 4, Len: 1024},
			notNull:              false,
			allowCommitTimestamp: false,
		},
		lastName: columnDescriptor{
			columnID:             "LastName",
			columnType:           spansql.Type{Array: false, Base: 4, Len: 1024},
			notNull:              false,
			allowCommitTimestamp: false,
		},
		singerInfo: columnDescriptor{
			columnID:             "SingerInfo",
			columnType:           spansql.Type{Array: false, Base: 5, Len: 9223372036854775807},
			notNull:              false,
			allowCommitTimestamp: false,
		},
	},
	albums: albumsTableDescriptor{
		tableID: "Albums",
		singerId: columnDescriptor{
			columnID:             "SingerId",
			columnType:           spansql.Type{Array: false, Base: 1, Len: 0},
			notNull:              true,
			allowCommitTimestamp: false,
		},
		albumId: columnDescriptor{
			columnID:             "AlbumId",
			columnType:           spansql.Type{Array: false, Base: 1, Len: 0},
			notNull:              true,
			allowCommitTimestamp: false,
		},
		albumTitle: columnDescriptor{
			columnID:             "AlbumTitle",
			columnType:           spansql.Type{Array: false, Base: 4, Len: 9223372036854775807},
			notNull:              false,
			allowCommitTimestamp: false,
		},
	},
	songs: songsTableDescriptor{
		tableID: "Songs",
		singerId: columnDescriptor{
			columnID:             "SingerId",
			columnType:           spansql.Type{Array: false, Base: 1, Len: 0},
			notNull:              true,
			allowCommitTimestamp: false,
		},
		albumId: columnDescriptor{
			columnID:             "AlbumId",
			columnType:           spansql.Type{Array: false, Base: 1, Len: 0},
			notNull:              true,
			allowCommitTimestamp: false,
		},
		trackId: columnDescriptor{
			columnID:             "TrackId",
			columnType:           spansql.Type{Array: false, Base: 1, Len: 0},
			notNull:              true,
			allowCommitTimestamp: false,
		},
		songName: columnDescriptor{
			columnID:             "SongName",
			columnType:           spansql.Type{Array: false, Base: 4, Len: 9223372036854775807},
			notNull:              false,
			allowCommitTimestamp: false,
		},
	},
}

type DatabaseDescriptor interface {
	Singers() SingersTableDescriptor
	Albums() AlbumsTableDescriptor
	Songs() SongsTableDescriptor
}

type databaseDescriptor struct {
	singers singersTableDescriptor
	albums  albumsTableDescriptor
	songs   songsTableDescriptor
}

func (d *databaseDescriptor) Singers() SingersTableDescriptor {
	return &d.singers
}

func (d *databaseDescriptor) Albums() AlbumsTableDescriptor {
	return &d.albums
}

func (d *databaseDescriptor) Songs() SongsTableDescriptor {
	return &d.songs
}

type SingersTableDescriptor interface {
	TableName() string
	TableID() spansql.ID
	ColumnNames() []string
	ColumnIDs() []spansql.ID
	ColumnExprs() []spansql.Expr
	SingerId() ColumnDescriptor
	FirstName() ColumnDescriptor
	LastName() ColumnDescriptor
	SingerInfo() ColumnDescriptor
}

type singersTableDescriptor struct {
	tableID    spansql.ID
	singerId   columnDescriptor
	firstName  columnDescriptor
	lastName   columnDescriptor
	singerInfo columnDescriptor
}

func (d *singersTableDescriptor) TableName() string {
	return string(d.tableID)
}

func (d *singersTableDescriptor) TableID() spansql.ID {
	return d.tableID
}

func (d *singersTableDescriptor) ColumnNames() []string {
	return []string{
		"SingerId",
		"FirstName",
		"LastName",
		"SingerInfo",
	}
}

func (d *singersTableDescriptor) ColumnIDs() []spansql.ID {
	return []spansql.ID{
		"SingerId",
		"FirstName",
		"LastName",
		"SingerInfo",
	}
}

func (d *singersTableDescriptor) ColumnExprs() []spansql.Expr {
	return []spansql.Expr{
		spansql.ID("SingerId"),
		spansql.ID("FirstName"),
		spansql.ID("LastName"),
		spansql.ID("SingerInfo"),
	}
}

func (d *singersTableDescriptor) SingerId() ColumnDescriptor {
	return &d.singerId
}

func (d *singersTableDescriptor) FirstName() ColumnDescriptor {
	return &d.firstName
}

func (d *singersTableDescriptor) LastName() ColumnDescriptor {
	return &d.lastName
}

func (d *singersTableDescriptor) SingerInfo() ColumnDescriptor {
	return &d.singerInfo
}

type AlbumsTableDescriptor interface {
	TableName() string
	TableID() spansql.ID
	ColumnNames() []string
	ColumnIDs() []spansql.ID
	ColumnExprs() []spansql.Expr
	SingerId() ColumnDescriptor
	AlbumId() ColumnDescriptor
	AlbumTitle() ColumnDescriptor
}

type albumsTableDescriptor struct {
	tableID    spansql.ID
	singerId   columnDescriptor
	albumId    columnDescriptor
	albumTitle columnDescriptor
}

func (d *albumsTableDescriptor) TableName() string {
	return string(d.tableID)
}

func (d *albumsTableDescriptor) TableID() spansql.ID {
	return d.tableID
}

func (d *albumsTableDescriptor) ColumnNames() []string {
	return []string{
		"SingerId",
		"AlbumId",
		"AlbumTitle",
	}
}

func (d *albumsTableDescriptor) ColumnIDs() []spansql.ID {
	return []spansql.ID{
		"SingerId",
		"AlbumId",
		"AlbumTitle",
	}
}

func (d *albumsTableDescriptor) ColumnExprs() []spansql.Expr {
	return []spansql.Expr{
		spansql.ID("SingerId"),
		spansql.ID("AlbumId"),
		spansql.ID("AlbumTitle"),
	}
}

func (d *albumsTableDescriptor) SingerId() ColumnDescriptor {
	return &d.singerId
}

func (d *albumsTableDescriptor) AlbumId() ColumnDescriptor {
	return &d.albumId
}

func (d *albumsTableDescriptor) AlbumTitle() ColumnDescriptor {
	return &d.albumTitle
}

type SongsTableDescriptor interface {
	TableName() string
	TableID() spansql.ID
	ColumnNames() []string
	ColumnIDs() []spansql.ID
	ColumnExprs() []spansql.Expr
	SingerId() ColumnDescriptor
	AlbumId() ColumnDescriptor
	TrackId() ColumnDescriptor
	SongName() ColumnDescriptor
}

type songsTableDescriptor struct {
	tableID  spansql.ID
	singerId columnDescriptor
	albumId  columnDescriptor
	trackId  columnDescriptor
	songName columnDescriptor
}

func (d *songsTableDescriptor) TableName() string {
	return string(d.tableID)
}

func (d *songsTableDescriptor) TableID() spansql.ID {
	return d.tableID
}

func (d *songsTableDescriptor) ColumnNames() []string {
	return []string{
		"SingerId",
		"AlbumId",
		"TrackId",
		"SongName",
	}
}

func (d *songsTableDescriptor) ColumnIDs() []spansql.ID {
	return []spansql.ID{
		"SingerId",
		"AlbumId",
		"TrackId",
		"SongName",
	}
}

func (d *songsTableDescriptor) ColumnExprs() []spansql.Expr {
	return []spansql.Expr{
		spansql.ID("SingerId"),
		spansql.ID("AlbumId"),
		spansql.ID("TrackId"),
		spansql.ID("SongName"),
	}
}

func (d *songsTableDescriptor) SingerId() ColumnDescriptor {
	return &d.singerId
}

func (d *songsTableDescriptor) AlbumId() ColumnDescriptor {
	return &d.albumId
}

func (d *songsTableDescriptor) TrackId() ColumnDescriptor {
	return &d.trackId
}

func (d *songsTableDescriptor) SongName() ColumnDescriptor {
	return &d.songName
}

type ColumnDescriptor interface {
	ColumnID() spansql.ID
	ColumnName() string
	ColumnType() spansql.Type
	NotNull() bool
	AllowCommitTimestamp() bool
}

type columnDescriptor struct {
	columnID             spansql.ID
	columnType           spansql.Type
	notNull              bool
	allowCommitTimestamp bool
}

func (d *columnDescriptor) ColumnName() string {
	return string(d.columnID)
}

func (d *columnDescriptor) ColumnID() spansql.ID {
	return d.columnID
}

func (d *columnDescriptor) ColumnType() spansql.Type {
	return d.columnType
}

func (d *columnDescriptor) ColumnExpr() spansql.Expr {
	return d.columnID
}

func (d *columnDescriptor) NotNull() bool {
	return d.notNull
}

func (d *columnDescriptor) AllowCommitTimestamp() bool {
	return d.allowCommitTimestamp
}
